### PR TITLE
Add InlineValue objects to generated LSP

### PR DESCRIPTION
**Pull request by zobo**

### CODE REVIEW

**Comment by dantleech** [comment]
Assume all the PHP code is generated?

**Comment by zobo** [comment]
Ofcourse. But I have not been able to try it in the project yet. 
Maybe I can write a github actions to perform at least a php lint test.

**Comment by zobo** [comment]
And for that matter, also a generate + check for no git changes test.

**Comment by dantleech** [comment]
it should be fine, we run PHPStan on it and there are some smoke tests. tbh I'm constantly amazed this works as well as it does :laughing:

**Comment by dantleech** [comment]
would be good to run some B/C checks to the pipeline -- however when upgrading the TS code occasionally the constructor argument order can change, and not really sure how to prevent that easily. In such cases I just sync all the phpactor code to the new version and try and use named parameters :roll_eyes:

**Pull request merged**
